### PR TITLE
Support for SpecFlow 3.3

### LINKED ISSUE #49: Breaking change in SpecFlow 3.3.57
**Describe the bug**
When upgrading SpecFlow to version 3.3.57 the constructor for ScenariInfo is changes from:
public ScenarioInfo(string title, string description, params string[] tags)
to:
public ScenarioInfo(string title, string description, string[] tags, IOrderedDictionary arguments)

This results in a failure to create the
private static readonly ScenarioInfo EmptyScenarioInfo = new ScenarioInfo(string.Empty, string.Empty);
in Allure.NUnit/AllureSpecFlow/PluginHelper.cs

**To Reproduce**
Run any scenario with this package combination:
```
    <PackageReference Include="Noksa.NUnit.Allure" Version="3.1.0" />
    <PackageReference Include="Noksa.NUnit.SpecFlow3" Version="1.1.5" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
    <PackageReference Include="SpecFlow" Version="3.3.57" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.3.57" />
    <PackageReference Include="SpecFlow.NUnit" Version="3.3.57" />
```

### PR DESCRIPTION
**Pull request by DanielVuurboom**
Fixes https://github.com/Noksa/Allure.NUnit/issues/49
* Upgrade SpecFlow to 3.3.30
* Upgrade .net FrameWork to 4.6.1 because 4.5 is no longer supported by SpecFlow
* Fix ScenarioInfo construction

### CODE REVIEW

**Comment by Noksa** [comment]
Hi.
Sorry for delay.
I'll look at this request soon.

**Comment by amvi88** [comment]
Hello, this PR solves some of our issues trying to upgrade SpecFlow see [#1939](https://github.com/SpecFlowOSS/SpecFlow/issues/1939) and [1912](https://github.com/SpecFlowOSS/SpecFlow/issues/1912). Would you consider adding these changes to your repo?

**Review by Noksa — APPROVED** [review]

**Comment by Noksa** [comment]
@amvi88 
@DanielVuurboom 
Merged

**Comment by amvi88** [comment]
Thank you!

**Pull request merged**
